name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::814207925733:role/og-ec2
          aws-region: us-east-1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t sgx30/og-ec2 .
      - name: Publish Image to Docker Hub
        run: docker push sgx30/og-ec2:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker image pull sgx30/og-ec2:latest
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name ogContainer sgx30/og-ec2
