name: CICD

on:
  push:
    branches: -main

jobs:
  build:
    runs-on:ubuntu-latest
    steps:
      -name: Checkout Source
        uses: action/checkout@v3
      -name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      -name: Build Docker Image
        run: docker build -t sgx30/og-ec2 .
      -name: Publish Image to docker hub
        run: docker push sgx30/og-ec2:latest


deploy:
  needs: build
  runs-on: aws-ec2
  steps:
    -name: Pull image from Docker Hub
      run: docker pull sgx30/og-ec2
    -name: Run Docker Container
      run: docker run -d -p 3000:80 --name ogContainer sgx30/og-ec2
