name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Secrets from AWS Secret Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            DOCKER_SECRETS,arn:aws:secretsmanager:us-east-1:814207925733:secret:og-ec2-TqzZ8G
          parse-json-secrets: true

      - name: Debug
        run: |
          echo "Secrets Output: ${{ steps.get-aws-secrets.outputs.secret }}"
          echo "Error Output: ${{ steps.get-aws-secrets.outputs.error }}"

      - name: Check for Prod
        run: |
          echo "Docker Username: $DOCKER_USERNAME"

      - name: Login to Docker Hub
        run: docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t sgx30/og-ec2 .

      - name: Publish Image to Docker Hub
        run: docker push sgx30/og-ec2:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker image pull sgx30/og-ec2:latest
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name ogContainer sgx30/og-ec2
